### ISSUE TITLE
After operator talkback to before operator need pass data when type equal 1.

### ISSUE THREAD

**Issue by janryWang** [callbag/callbag#20]
In some scenarios, you want the back operator to communicate with the front operator and pass the message, so all the operator talkback is required to support the transfer of data.

**Comment by staltz** [comment]
You mean that all the operators need to support pullables?

**Comment by janryWang** [comment]
Yes, in some cases, this communication capability is needed

**Comment by staltz** [comment]
Yeah, operators need to individually inform whether they support pullables or listenables or both. Since this is just a spec, it allows any of those.

If you need guarantees that operators support always both, then you need to create a curated list of operators or just a repository that has multiple operators.

Remember, this is a community spec, not a library.
