### ISSUE TITLE
Errors and Termination

### ISSUE THREAD

**Issue by jordalgo** [callbag/callbag#41]
First, Callbags are absolutely marvelous! I'm so jealous you thought of this first because it's so simple and elegant it makes me cry a little 😂 but also so happy they are in the world now. Really great stuff; I can't wait to re-write everything using this model 🎉 

A couple of questions (mostly around the same topic):
- Why are errors tied to termination? This is a carry-over from Observables but perhaps Callbags should be not be opinionated about such things. When a relationship is terminated the second argument doesn't necessarily have to indicate error but rather some undefined (type: any) payload that could be some completion data or an error. This is currently the case for data passing (type 1) as any puller or listener has to check 'data' if the producer wants to send any non-terminating error messages. 
- I'm sure you've considered this but perhaps the introduction of a 4th type could be errors  😄 -- 0) handshake 1) data 2) error 3) termination. I've advocated for this style before in other libs/proposals and TBH, I'm asking again because I haven't understood and/or been satisfied with the provided answers. Doing something like this would be in line with [Railway Oriented Programming](https://fsharpforfunandprofit.com/rop/) and make Callbag producers more flexible in terms of the message types they send down (not having to terminate to send an error) and operators could just pass the errors along without even having to be modified from their current implementations:
```
const map = f => source => (start, sink) => {
  if (start !== 0) return;
  source(0, (t, d) => {
    sink(t, t === 1 ? f(d) : d)
  });
};
```
I'm a firm believer in this idea because unless you're incorporating some kind of `try/catch` system in all operators/producers any "error" sent down the pipe is an operational error as there is no guidance on it being re-thrown when it reaches a consumer that doesn't handle it (remember unhandled Promise rejections are thrown errors -- even though they can be caught later). Additionally (and this argument is coming back to me as I type), if your producer wants to send down more structured payloads e.g. `{ data, error }` -- your operators become a lot less pretty e.g.
```
 const source = map(x => {
  if (x.data) { 
    return { ...x, data: x.data * 0.1 };
  } else { 
    return x; 
  })(fromIter([{ data: 10}, {error: 'ran out of numbers'}]));
```
I feel like if Callbags aren't going to be opinionated at all about errors, then at least they shouldn't specify that errors represent the payload argument in a terminating message.

Anyway, very curious to hear your thoughts on this and my apologies if you've heard this before from me and it just sounds like a broken record.

**Comment by isiahmeadows** [comment]
I was about to post a bug like this, but this one hits the spot. I was wanting to make a high-level combinator to allow creating pipelines to encourage railway-oriented programming, but it's kind of hard to model non-fatal logic errors without either allocating a completion-like object or having them builtin. And for creating transform pipelines, it's pretty hard to model them to be both error-tolerant and performant when I have to constantly allocate completion objects (without replacement) any time my operator isn't [surjective](https://en.wikipedia.org/wiki/Surjective_function). Some concrete examples of where I'd have to allocate are for the last value for `scan`, each nested value in `flatMap`, and each emit from `interval` and `repeat`. And this is assuming I can reuse results I send (which isn't safe, but it's possible if transparent).

Or, TL;DR: I'd like to see a non-fatal error added, so I don't have to worry about performance here.

**Comment by franciscotln** [comment]
@jordalgo FYI the experimental branch of RxJs (probably what will become v7) is written with Callbags and the type 3 represents errors as you suggested
https://github.com/ReactiveX/rxjs/blob/experimental/modules/core/internal/types.ts

**Comment by staltz** [comment]
Hi @jordalgo, thanks for raising this topic in a nice way and with examples.

The reason why Callbags have 0/1/2 types only is because this is apparently the minimum required (hence most general) for bidirectional communication. Essentially, those types express all possible bidirectional interactions: first (0) the two sides introduce themselves, then (1) they send stuff to each other, then (2) one of them proposes to stop the conversation.

Notice that this frame can fit the type of interactions you were suggesting, because I simply talked about "sending stuff". Of course, the concern is how, and one way is to send structured payloads `{data, error}` and *this would actually work*, but I'll get back to that argument soon.

> I feel like if Callbags aren't going to be opinionated at all about errors, then at least they shouldn't specify that errors represent the payload argument in a terminating message.

I know the spec says "second argument is either undefined (signalling termination due to success) or any truthy value (signalling *termination due to failure*)." but the way I see it in practice is that the argument is the *reason* for termination. It's just metadata about why the termination occurred. It does not necessarily indicate error, but it often does indicate, because there is *usually just one* successful termination status. But in a hypothetical situation, you may want to indicate successful termination with different reasons. This is a bit similar to UNIX processes that [exit with a status](http://pubs.opengroup.org/onlinepubs/009695399/functions/exit.html). This is also like Promises that, when rejected, give a *reason* for rejection. You could conceptually think of Promises as sending an `undefined` reason when resolving successfully, but that doesn't make much sense for Promises because there is only one value delivered.

Now talking about how to implement non-fatal multiple error emissions, one way is by sending a structured payload, as you described. The other way is by sending `type=11, payload=nonfatalerror` (type 11 chosen as to avoid the reserved codes and because 11 is "1" but higher. you could choose any other number though). **Both** of these alternatives would mean that some operators would need to be rewritten, others (like map) could stay untouched. The Callbag spec as is does not give any guarantees regarding non-fatal railway oriented errors, but that's just because Callbag spec is more general than that.

In other words, this whole issue is about *adding more guarantees into* the Callbag spec, and I think you could do that with a *specialization of the spec* which is backwards compatible with the original spec. I'm probably confusing you with this, but I want to highlight a point from a [blog post about Callbags](https://egghead.io/articles/comparing-callbags-to-rxjs-for-reactive-programming):

> Generality: Promise < Observable < Callbag < Function

Functions can do anything that those on the left can do. Callbags can do anything that Observables and Promises can do. Observables can do anything that Promises can do. But it also works the other way around, *because* promises are so "not-general", they have a lot of guarantees and predictable behaviors.

> Predictability: Function < Callbag < Observable < Promise

By suggesting that Callbags can have non-fatal errors, I think you're looking for Callbags that have one more guarantee, a *less general* Callbag spec. So it seems the best way would be to keep the current spec immutable, then create a new spec which adds one more guarantee on top of Callbags, in a backward compatible style. For instance the type=11 suggestion would do. The benefit is that every Callbag-with-railways would also be a Callbag, so plain Callbag operators like `map` would work on Callbag-with-railways because `map` doesn't make assumptions beyond the plain spec.

How does that sound like?

**Comment by jordalgo** [comment]
@staltz Thanks for the detailed and quick response! My first reaction is that everything you said sounds perfectly reasonable 👍 I do have some additional follow-up questions/comments:

**Termination Errors:**

> the way I see it in practice is that the argument is the reason for termination. It's just metadata about why the termination occurred. 

This is great and I think the spec should be updated with this language or idea (happy to put up a PR) as it makes a lot more sense (at least to me) about the termination event and Callbags being non-opinionated about the payload.

**Error Type:**

> By suggesting that Callbags can have non-fatal errors, I think you're looking for Callbags that have one more guarantee, a less general Callbag spec. So it seems the best way would be to keep the current spec immutable, then create a new spec which adds one more guarantee on top of Callbags, in a backward compatible style.

Good call. I think this suggestion makes a lot of sense and I have a feeling I'm going to spend some vacation time working on this new spec 😄 

Just to play devil's advocate, let's say Callbags got less general and added this 4th type to indicate an 'error' in the communication. Is the worry that in doing this you might be opening the door for other types that may try to get crammed into the spec (type-creep)? I understand that the 3 current types are "the minimum required for bidirectional communication" but is there a larger risk introducing an 'error' type which **might** make Callbags more useful (and according to @franciscotln, RxJs has already started doing)? I guess I'm just thinking of cognitive overhead of people starting to use Callbags and there being sub-class specs with slightly less general behavior. I'm also scratching my head a bit in trying to think of what you give up (in terms of generality) if you add this error type. Data payloads can still be structured in anyway the producer sees fit but with error codes/types you get a slightly more structured "conversation" which make operator use safer and clearer opportunities to end the conversation on either side (hope that makes sense).

Again, I'm all for the building-block approach and creating the most basic structure to build off e.g. Railway Callbags < Callbags < Function -- I'm just sorta thinking aloud here.

Also, and I admit I didn't do much digging, I don't quite understand the reserved codes e.g. why '11' in stead of '3' like this RxJs branch is using? Do you have some world wide web links for more info on this?

**Comment by jordalgo** [comment]
(off-topic) @franciscotln - Are all errors terminating by default in this new RxJs experimental branch 👼 ?

**Comment by franciscotln** [comment]
@jordalgo looking at the map operator [here](https://github.com/ReactiveX/rxjs/blob/experimental/modules/core/internal/operators/map.ts) I would say that it terminates by default.

**Comment by jordalgo** [comment]
@franciscotln Actually, in that link it looks like it only terminates if the mapping function being applied to the next value throws; then it sends an error and terminates. Otherwise it's a pass through.

**Comment by franciscotln** [comment]
@jordalgo Sorry, I misunderstood your question then :-) I thought terminating (after an error).

**Comment by staltz** [comment]
> Is there a larger risk introducing an 'error' type which might make Callbags more useful?

It would make Callbags more useful, but less powerful. The opposite of useful is not less useful, it's "more power". :) See this talk by Cheng Lou: https://hooktube.com/watch?v=mVVNJKv9esE So it means moving towards usefulness is not always a necessary win, it's really about what you want from an abstraction.

Regarding should we change the spec or not, I prefer that projects are immutable, and to use forks (compatible forks or not) as a path to move forwards. If we *mutate* the spec, we break existing blog posts, conference talks, as well as existing code out there in the wild. The negative effects of mutation, such as breaking references to old content, apply not only to variables in memory, but also to open source projects.

**Comment by isiahmeadows** [comment]
@staltz I have a few ideas related to this, but I filed it in a separate bug: #42

**Comment by jordalgo** [comment]
> I believe Ben Lesh is not changing the semantics of error treatment, it would still be fatal errors then. Even if this map operator passes through errors, I think the upstream source would emit only one error.

I had a feeling :)

> If we mutate the spec, we break existing blog posts, conference talks, as well as existing code out there in the wild. 

Makes sense. Thanks again for the timely and thoughtful responses. Going to look into what @isiahmeadows is proposing before forking anything.
