### ISSUE TITLE
What if an exception is thrown during callbag execution?

### ISSUE THREAD

**Issue by mattflix** [callbag/callbag#45]
The callbag spec seems silent about how to deal with exceptions thrown during callbag execution.

For example, if the invocation of `someCallbag(1, dataPayload)` (i.e., a data delivery) somewhere in the middle of a callbag chain throws, is there any expectation about what should happen with the thrown error, or the overall execution of the chain?

Actually, same question for any of the defined payload types (0, 1, and 2), since any of these types of processing may encounter an exception.

**Comment by staltz** [comment]
The callbag spec concerns the interface, the medium of communication, not the internal implementation of each callbag. I think for exceptions, you could wrap it in a try-catch and in the catch send the error in a type=2 message.

**Comment by mattflix** [comment]
I think this topic warrants further discussion....  somewhere.  What is the appropriate forum in which to have this discussion?

Is the view here that it is only appropriate to have a discussion about error-handling with callbags in relation to a particular callbag's implementation?

In regards to a cohesive approach to error-handling with callbags, should such discussion be had only in regards to a particular family of callbags that, say, are all internally designed to provide a cohesive error-handling behavior (whereas another family of callbags may not)?

**Comment by mattflix** [comment]
I am not referring a specific family of callbags...  just imagining one with some kind of cohesive approach to dealing with exceptional execution paths, versus another family that does not.  But, to take one family in particular, we could talk about the `callback-basics` package.

If an exception is thrown, for example, out of the transform function passed to the `map` operator from `callback-basics` (and when using only other callbags from the same package, to constrain the scenario) the error is not propagated to any callbag's `type=2` logic (as one might expect).  Instead, it is thrown all the way out of whatever invoked callbag logic is currently on the stack, and the program ultimately terminates with an unhandled error.  (This is from my own experimentation with the package.)

You mentioned (earlier, above) that the callbag spec is intended to define a "medium of communication".  Do you not consider exiting from the invocation of any callbag (`type=0|1|2`, or any other) via an exception to be an integral part of that communication?

IMO, the spec should say _something_ about exceptional execution paths, since they are an intrinsic aspect of communicating via function call.  One that every implementator and user will run up against, and wonder what to do or what will happen -- specifically in relation to behavior _and state_ of their callbags.

For instance, one thing the spec might say is, "Callbag invocations should not throw.  All exceptions should be caught internally and propagated, if desired, only via other callbag invocations."  I am NOT necessarily advocating that, but it would (as an illustration of something that could) answer _all_ questions about how to deal with exceptional execution paths in callbags.

Personally, I would actually prefer a somewhat more flexible approach, one that actually permitted exceptions to be thrown out of callbag invocations (as there are some interesting optimizations to be had) but also specified (or at least gave clear guidelines) about what it means when this occurs (i.e., what is being _communicated_), with the natural implication that this would then provide enough information about what correct actions(s) any given callbag could take next.

For example, with the current spec's silence about exceptional execution paths, if a `type=0` invocation throws, even if caught by the caller, the caller really has no way to know what state the full "stack" of callbags is in, what state the other callbags can be expected to be in, what possible actions are correct to take, etc..  However, if the guideline (or spec) were something like, "No `type=0` callbag invocation should throw an exception without first disposing of any used resources, including other callbags", then the catcher would know both what it can do, and probably also what it should do.

I've implemented enough of my own callbags with internal exception handling to know that this is a real issue.  I know that one cannot take exceptional execution paths into consideration in some callbags, but not others (or consider them in different ways in the others), and expect a cohesive outcome.

As a thought exercise (or better yet, an actual exercise), given a chain of callbags, where several in the chain allocate expensive resources that must be cleaned up when the overall execution of the chain has finished, how can we ensure that all the appropriate `type=2` logic is invoked (to perform the required resource cleanup) if an error occurs, including an exception thrown from, say, the transform function of the `map` operator from `callback-basics`?

**Comment by franciscotln** [comment]
@mattflix  I remember having a similar conversation on the "cycleJs" gitter channel. If I'm not mistaken at that time @staltz said that the only callbag source that propagates the error is `fromPromise` because a promise can fail. I also remember him saying that you can implement all the callbags using a `try catch` and propagating errors if you wish so, but it was also a question of speed. Try catches slow down the execution and as said: they should not throw.
I know $hit happens and you can have runtime errors due to some problem in a mapper function, for example.
My solution for this was the following:
I haven't forked all callbags and implemented my own versions with try catch blocks, I created a `safePipe` instead since all executions will pass throw it anyway. Inside this safePipe I wrap the original callbags and use tryCatch.
If you are very concerned about speed (not my case) then you should not use this.
```js
const safePipe = (...cbs) => {
  const originalSource = cbs.shift();
  const originalSink = cbs.pop();

  const composedSource = cbs.reduce(
    (source, operatorSink) =>
      operatorSink((start, sink) => {
        if (start !== 0) return;
        let talkback;
        source(0, (t, d) => {
          if (t === 0) {
            talkback = d;
          }
          if (t === 1) {
            try {
              sink(t, d);
            } catch (e) {
              sink(2, e);
              if (typeof talkback === "function") talkback(2);
            }
            return;
          }
          sink(t, d);
        });
      }),
    originalSource
  );

  return originalSink(composedSource);
};

export default safePipe;
```
Working example here: https://codesandbox.io/s/3kq9xpjy3q
For my use cases this is enough :-)

**Comment by mattflix** [comment]
@franciscotln, a "safe pipe" is an interesting idea, thanks.

Your comments about performance are also noted.  But, if you are suggesting that the callbag spec purposely ignores exceptional execution paths in the interest of speed, this would seem to be a dubious tradeoff.  Sure, there is a class of useful programs that simply terminate when any exception occurs, but most programs are probably not part of this class.  (No program I have ever be paid to contribute to falls into this class.)  This would make callbags written to the base callbag spec nearly useless for creating production software.

As @staltz says, anyone if free to fork the base spec and define a "callbags++" spec, in this case perhaps "callbags with exception-handling".  However, IMO, the expected outcomes when exceptions thrown are from callbags really should be part of the base spec (since nobody can escape that reality).

----

One note specifically about your above code...

You only seem to catch exceptions thrown during `type=1` invocation (data delivery).  I count six other unguarded callbag invocation sites, which will of course be multiplied by the number of sources/sinks in the pipe.  Did you intend to also handle cases where callbag initialization or cleanup (`type=0|2`) might throw?

And, while your "safe pipe" idea might help is certain cases, it won't help with callbags that combine with others in ways that don't involve a pipe (for example, the `sample` operator from `callbag-basics`, which talks directly to a third callbag to drive pulls from its source callbag).  Many other similar "pipeless" interactions are also possible and, for a cohesive outcome, all would need to follow the same rules when dealing with exceptions.

**Comment by franciscotln** [comment]
> it won't help with callbags that combine with others in ways that don't involve a pipe (for example, the sample operator from callbag-basics, which talks directly to a third callbag to drive pulls from its source).
> 

That's no quite true :-) This works and the error is caught. Check the same codeSandbox link
```js
safePipe(
  interval(1000),
  sample(fromIter("hello")),
  map(x => x.y.z.toUpperCase()),
  subscribe({
    next(v) {
      console.log("next", v);
    },
    error(e) {
      console.log("error", e.message);
    }
  })
);
```

**Comment by mattflix** [comment]
Yes, you have ultimately caught the exception in the safe pipe `try/catch`, but my point is that it passed right through other callbags that potentially should have taken it into account as well.

The safe pipe achieves the very basic goal of keeping the program from terminating, but doesn't necessarily keep all callbags in an internally consistent state, which, by extension, would keep the program in a consistent state.

**Comment by franciscotln** [comment]
> However, this wrapping/handling does not occur for exceptions thrown from type=0|2 invocations, which are not even caught.
>
Yes, that's correct. I'm assuming the initial source and the sink will not throw.
For example calling `safePipe(fromIter()) `without argument, it will throw because `fromIter` expects an iterable. But IMO these are already extreme cases, it means one does not know how to correctly use the source.
Regarding errors thrown in the sink: this you can be achieved by ultimately wrapping the sink code inside a try catch. Something like:
```js
safePipe(
 ...someSources,
  forEach((v) => {
    try {
      // do something with v
    } catch(e) {
      // do something else with this error
    }
  })
)
```

**Comment by mattflix** [comment]
To be clear, I am not concerned with unintentional programming errors (like your example of not using a source correctly).  If you put code together incorrectly such that a crash results, then undefined behavior is what you get.

What I am concerned with is callbags being _intentionally_ implemented to throw exceptions, for example:

```javascript
function coolOper(source) {
  return source =>
    t => {
      if (t === 0) {
        if ( /* cool initialization logic failed */ ) {
          throw new Error(`Sorry, coolOper failed to initialize`); // WRONG!
        }
     }
  }
}
```

I think the spec should be clear and says that this is an invalid `type=0` implementation.  That is, the spec should state that callbag initialization should not intentionally throw (and should also not leak exceptions).

Indeed, @staltz has suggested previously (was my interpretation) that the following is how one "should" properly fail callbag initialization:

```javascript
function coolOper(source) {
  return source =>
    (t, talkback) => {
      if (t === 0) {
        if ( /* initialization logic failed */ ) {
          talkback(0, /* something */);
          talkback(2, /* the error */);
          return;
        }
     }
  }
}
```

However, I'm not clear what the `/* something */` argument should be...  I mean, it should be a _some_ callbag as required by the spec.  But, should it perhaps be the "null callbag" (e.g., a no-op).

**Comment by mattflix** [comment]
Similarly, if the cleanup logic of any callbag encounters a (non-programming) error, I think the only reasonable course of action is to continue to propagate the `type=2` invocation, either supplying or replacing the (error) argument.

**Comment by mperktold** [comment]
I really like the idea of a `safePipe`.

I had similar concerns about how to propagate errors and came to a different solution you might be interested in.
Namely, I created an operator [`graceful`](https://github.com/mperktold/callbag-graceful), which takes a source and returns an equivalent one but with proper error handling. In other words, you should be able to define `safePipe` as:

```javascript
const safePipe = (...cbs) => pipe(...cbs.map(graceful))
```

**Comment by mattflix** [comment]
These mitigations are great (and clever) but they should not be necessary, IMO.

I think their apparent necessity only highlights the fact that callbag implementers have no clear guidelines on how to actually handle errors, nor any validation suite (or something) that can be used to verify their error-handling (and even non-error) correctness.

I really like callbags, but I think this fundamental flaw in the spec (that is how significant I think it is) to not specify what should happen in exceptional code paths, will lead to a world of unreliable and mostly "toy" operator implementations -- unsuitable for use in production software.

I guess having "curated" collections of "known well-implemented" callbags would be a way around this, but seems to defeat the idea of "universal interoperability".  Likewise, having to wrap everything in extra operators (e.g., `graceful`), just to achieve basic correctness, likely comes at a very real performance cost.

**Comment by StreetStrider** [comment]
@mattflix I basicly agree with everything you postulate, but must notice that any solution with exception handling will cost some perf. The only way for users not to pay it is to move this burden to implementors, like this is done now.

Other thing what I mark that @staltz is trying to make this thing portable to another langages, so error handling should be portable as well.

There's other strong opinion that users must implement error handling and pass `Either<T, E>` as value. Some related discussion paldepind/flyd#171

**Comment by mattflix** [comment]
The spec is mostly clear that "logical errors" that should be forwarded as `type=2` with a (truthy) error argument.  That is, your source/operator encounters an internal error generating the next item, then emit `type=2` with an error instead.  Fine.  I am fine with that part.  That said, the spec is not clear about (doesn't really say) what should happen when `type=0` invocation encounters an error.

But...  what I am more concerned about is lack of specificity about what should happen when a callbag invocation (of any kind, `type=0|1|2` or other) throws an exception.

Either exceptions are allowed/expected with specific behaviors/invariants that the thrower, catcher, or passee should adhere to (i.e., which would lead to defined behavior, assuming correct implementations per this adherence) or exceptions are not allowed/expected (i.e., which can only lead to undefined behavior).

Right now, the spec does not seem to say.

**Comment by mperktold** [comment]
> Likewise, having to wrap everything in extra operators (e.g., `graceful`), just to achieve basic correctness, likely comes at a very real performance cost.

You can also see it the other way around: catching exceptions is something you can opt-in, so you can gain performence by not doing it in cases where you don't need it, which would be many.

I guess most of the times exceptions do not come from within operators, but from the functions passed to operators. For example, you might have a callgag `pipe` with a `map` step, in which you use an existing function that converts one type to another, but throws if it cannot do so. Since you know the contract of that function, you can make sure that errors thrown from it are properly propagated down the pipe, e.g. using `graceful`, or manually using try-catch, but you don't have to do it for every step in the pipe.

Or, you could also use such an opt-in approach on a per-pipe level: if anywhere in the pipe a data delivery can throw, you use `safePipe`, otherwise you stick with `pipe`.

**Comment by mperktold** [comment]
I also agree that the spec could be clearer about exceptions.

However, I don't think it should require sources to catch all errors thrown in sinks. This would invalidate most of the current implementations, and require some boilerplate code in all of them to get it right.

I think that the nice thing about callbags (apart from the original idea) is that they can be implementet so easily and with very little code.

But to better address concerns about exceptions, maybe the spec should just clearly state that it does _not_ prescribe any specific behavior. Thus, it would explicitly leave it to the implementations to decide how to deal with exceptions.

On the other hand, there is no need to find a single solution for how to address exceptions in the spec. We can create a sub-specification, e.g. _Safe Callbags_, which inherits everything from the callbag specification but adds more strict rules regarding exceptions.

This is the other great thing about callbags: it's just "a reusable idea". 😸

**Comment by staltz** [comment]
There's too much in this thread for me to comment without having "internet commenting and email replying" as my full time job, so I'll pick some key things:

> callbag implementers have no clear guidelines on how to actually handle errors — @mattflix 

To goal of the Callbag spec is to specify the interoperability layer, and only the layer. Implementations guidelines are great, and this repo has one [markdown file separate](https://github.com/callbag/callbag/blob/master/getting-started.md) from the Readme, but it's still not within the concern of the spec how to write the internals. The only thing the spec is concerned is whether a function is "valid callbag interaction" or not. Also, there's absolutely no need to implement callbags with very succinct minified code, in fact there's another example in the getting started markdown that shows how to implement it with classes.

> I really like callbags, but I think this fundamental flaw in the spec (that is how significant I think it is) to not specify what should happen in exceptional code paths — @mattflix 

The spec does specify how exceptional code paths should be *passed between callbags*, because the spec is only concerned about what happens *between callbags*. Emphasis on *between*.

Whether an internal error should be signaled outwards is the decision of a callbag's implementation. Should simple JS syntax errors be caught and signaled as `type=2`? They could, but I wouldn't do that, specially if I use TypeScript to find these mistakes. But these syntax errors could. Server response errors should most likely be treated as `type=1` actually, but other kinds of actual "failures" like ENOENT could probably be signaled as `type=2`. But you can never treat all the possible errors, no try/catch can recover from `while(true){doSomethingSilly()}` and a subsequent crash. 

> Other thing what I mark that @staltz is trying to make this thing portable to another langages, so error handling should be portable as well. — @StreetStrider 

I'm not trying to port it to other languages, but other people are doing it and it's pretty cool.

PS: I like the `safePipe` idea, although one has to be careful not to trust it entirely, because there can be unfortunate `while(true){}` crashes too, and that's actually a possibility if one is implementing a synchronous pullable source.

**Comment by mattflix** [comment]
@staltz , I'm not (that is, I'm not directly or only) talking about how/when any given callback should make `type=2` invocations (to communicate an error).  You are correct, that is an internal implementation detail and is subject to the semantics of the callbag.

What I'm talking about is more basic...   What should happen when a callbag invocation throws an exception?

Are we to consider a callbag well-implemented (or even just within spec) if, for example, it throws an exception from a `type=0` invocation (e.g., failed to start) or a `type=2` invocation (e.g. failed to end)? 
 How will the rest of the callbag stack be reliably torn down in these cases?  Or, is this behavior (after an exception) simply left undefined?

In the case of `type=0`, should a callbag instead (of an throwing) return normally and later communicate the failure to initialize as a `type=2` emission?  Could it do either?  If yes, are callers then expected to create duplicate error-handling in both code paths?  (Note that this is much the same problem `rxjs` had when it allowed synchronous errors to be throw from `subscribe()`, before this was seen as a major mistake and fixed -- by communicating errors strictly via the `Observer.error()` channel.)
