### ISSUE TITLE
Control flow assumptions

### ISSUE THREAD

**Issue by RylinMirabel** [callbag/callbag#49]
Although it is bad practice to synchronously call callbacks everywhere due to potential call stack overflows, the spec does not disallow this. It seems like there is a widespread assumption that control flow returns to the calling function immediately due to asynchronity or [trampolining](https://github.com/staltz/callbag-from-iter). In [callbag-take](https://github.com/staltz/callbag-take), this assumption results in [multiple termination](https://repl.it/repls/TechnologicalExoticExponent). I propose some possible solutions to the conflict between this common assumption and the spec:

1. Write an "adapter" callbag to introduce asynchronity by using setTimeout(cb, 0)
2. Add restrictions on control flow to the spec

**Comment by mperktold** [comment]
I expressed similar concerns in #39.

The outcome of that discussion is that one should implement synchronous pullable sources using `from-iter` and a generator function, so ˋfrom-iterˋ would take care of preventing the stack from overflowing.

In an attempt to better document this problem, I created [callbag-pullable](https://github.com/mperktold/callbag-pullable), a spec that defines what a pullable callbag source is and how to correctly implement one in general.

Good catch regarding `take`!
I think this bug is not only related to calling callbacks synchronously.
When reaching the given number of items, it should set `end` before terminating the source.
You should probably create an issue or a pull request.

**Comment by staltz** [comment]
Hey @RylinMirabel thanks for the careful consideration of this topic, and specially the example code in repl.it, it makes it easier to discuss what is going on.

My diagnosis of that example is that the problem is not with `take`, instead the problem is `rangeInfinite` which implements a synchronous pullable (essentially conceptually equivalent to an Iterable), and such the best implementation would be `fromIter()`. See this repl.it, it only has 1 termination:

https://repl.it/repls/PrudentUnwittingQuotient

It is true that this Callbag spec is too powerful and comes with some [footguns](https://etherealmind.com/network-dictionary-footgun/), but I think the solution here is careful implementation, and not a catch-all solution like trampolining via setTimeout or a microtask scheduler. Plain JS functions also have footguns, and Callbags are merely a subset of Functions. Callbag is not built on this assumption that "*control flow returns to the calling function immediately due to asynchronity or trampolining*" because functions don't have that assumption. Another way of describing the Callbag spec is that it puts a few rules for *mutually recursive pairs of functions*, and recursion in functions can be either synchronous or asynchronous.

I've worked with other asynchronous trampolining libraries, such as RxJS version 4, and it comes with some drawbacks, e.g. the call stack is harder to understand and debug. In Promises, which schedule resolution always asynchronously, we lose power because synchronous yielding can no longer be expressed. This is a deep constraint that now affects many other parts of JavaScript, e.g. AsyncIterables. Because of that, it's hard to build the `merge()` operator for AsyncIterables (I've tried and have not figured it out so far), and means that pullable Callbags are more expressive than AsyncIterables.

**Comment by RylinMirabel** [comment]
I misused "trampoline", I actually meant the style used in callbag-from-iter, sorry for the confusion. The way callbag-from-iter avoids this issue is that it ensures only 1 invocation of each callbag data handler exists on the call stack at any time (e.g. stack, left is bottom: ...start invocations, callbag-from-iter source, callbag-take fromsource, callbag-foreach sink, callbag-take tosource, callbag-from-iter fromsink). I think this should be specified by the spec.

**Comment by staltz** [comment]
Actually that's what trampolining really means, so your original post was correct. But it's synchronous trampolining, because it uses a for loop. With your setTimeout suggestion, it would be async  trampolining, i.e. only 1 invocation of the sink on the call stack at any time, but this is achieved with setTimeouts.

The spec *could* talk about  sync trampolining, but that would be a spec dictating the *how*, not the *what*. Currently the spec describes the *what*, and both sync trampolining or async trampolining are valid solutions for that *what*. Basically I understand that this could be clarified, but I think it belongs to tutorials and documentation, not necessarily the spec. See for example that this repo contains another markdown doc on how to implement callbags. I'm in full agreement that we could talk about sync trampolining in that doc, not the spec doc.

**Comment by RylinMirabel** [comment]
I withdraw my previous suggestions, I think the following should be added to the spec:
---
Only 1 invocation of each callbag data handler may exist on the stack at any time.
---
Many callbag libraries assume this, and it doesn't place any burden on most existing libraries, because they will satisfy this requirement if the callbags they interact with also satisfy it (this includes sinks). It puts the onus to trampoline on sources.

**Comment by RylinMirabel** [comment]
Clarification: by "invocation of callbag data handler" I mean a call into talkback(1, data).

e.g. stack from top to bottom:
callbag-from-iter fromsink(1) --- data handler invocation
callbag-take fromsink(1) --- data handler invocation
callbag-foreach sink(1, data) --- data handler invocation
callbag-take fromsource(1, data) --- data handler invocation
callbag-from-iter source --- not data handler invocation
...start invocations

In this case, the requirement forces "callbag-from-iter" to resume from "callbag-from-iter source" rather than calling into "callbag-take fromsource" from "callbag-from-iter fromsink"

**Comment by staltz** [comment]
What's the purpose adding "Only 1 invocation of each callbag data handler may exist on the stack at any time." to the spec? To make implementations correct according to the current spec (i.e. version 1.2.0). It's useful, but it's only describing the means, not the goal. If we don't add that to the spec, and implementations don't use sync trampolining, then those implementations will be incorrect according to the spec. So in other words, the spec is already *complete*, we just need to improve documentation around how to implement it.

I'd gladly accept a PR to [getting-started.md](https://github.com/callbag/callbag/blob/master/getting-started.md) about sync trampolining in sources.

**Comment by RylinMirabel** [comment]
I need a clarification on your diagnosis that the problem in the repl is in the source. What I think is that the source behaves correctly according to the spec, and it is callbag-take that violates it.

Strictly speaking many current callbag libraries do not meet the current spec because they will behave out of spec if used synchronously without trampolining (such as callbag-take). In my opinion, if many libraries inadvertently make an assumption that can be included in the spec in a harmless way, it should be.

**Comment by staltz** [comment]
Interesting! I learned three things: (1) the spec currently doesn't forbid multiple termination, which is wrong, that's something we should update the spec with. (2) In my diagnosis of that repl.it, I think `callbag-take` is violating the spec and, (3) I found a simple fix for `callbag-take` that would would fix the repl.it without changing the source.

About (2), here's what my diagnosis: *if there exists any potential path in the control flow of the implementation of take() such that the spec would not be satisfied*, then it's take()'s responsibility. And that case existed because take's `sink` was synchronously recursive.

That said, I wouldn't go down the path of trying to fully determine which individual function is wrong, because in JavaScript it's often very hard to get that guarantee because it's so dynamic. This is similar to functional purity. It's tempting to say that the function `x => x * 3` is pure, but its purity depends on the arguments. See [this blog post](https://staltz.com/is-your-javascript-function-actually-pure.html) I wrote about that. So functional purity is a property of the *system* of arguments and functions, not the property of an individual function. Similarly, with callbags, even if we have a bunch of incorrectly implemented callbag functions, *as long as their* behavior as a system abides by the spec, they are correct. This is as much correctness as we can get in JavaScript, because the arguments can come with all sorts of hacks, that the alternative of adding robust assertions would add too much runtime overhead and implementation complexity.

**Comment by RylinMirabel** [comment]
The problem with callbag-take can indeed be [fixed](https://repl.it/repls/BrightRawArraylist) in one line. I agree that trying to cover all your bases in JavaScript is an exercise in futility. However, calling into functions synchronously without trampolining is hardly an abuse of JavaScript's quirks. I think that this disconnect between the spec and many libraries needs to be addressed.

**Comment by staltz** [comment]
Callbag-take fixed: https://github.com/staltz/callbag-take/commit/7d5377eeeb96f3b172e6b2f2fae911951b53cc08

> I think that this disconnect between the spec and many libraries needs to be addressed.

Yes, addressed in the non-spec docs.

**Comment by staltz** [comment]
See #50

**Comment by RylinMirabel** [comment]
I think your fix caused the bug that was fixed by the previous fix to resurface, which is that mutual termination will occur if the sink terminates callbag-take after callbag-take calls sink(1,d) when taken === max. To fix it you need to shift the !end condition check to before you send the termination signal.

**Comment by staltz** [comment]
> To fix it you need to shift the !end condition check to before you send the termination signal.

I don't understand, the `!end` condition check is already before sending the termination signal. And we would have needed tests for this commit: https://github.com/staltz/callbag-take/commit/205e5a3ad1dc2a04d149cc3760b86b822ccd29d7

**Comment by RylinMirabel** [comment]
Sorry, I mean just before sending the termination signal. [Here's](https://repl.it/repls/IvoryHurtfulLicenses) an example. I didn't see the tests file when writing the fix, sorry.

**Comment by RylinMirabel** [comment]
I think this [fix](https://repl.it/repls/BrightRawArraylist) addresses the problem, though it isn't ideal because the talkback(1,d) calls are not in tail position. As for the Callbag spec, I agree that we should highlight how synchronous sources might violate assumptions by Callbag authors rather than take the heavy-handed approach of changing the spec. Closing.
