### ISSUE TITLE
Address Error Handling In Spec?

### ISSUE THREAD

**Issue by zebulonj** [callbag/callbag#7]
1. This is beautiful. Elegant!

2. You may have intentionally omitted error handling from the spec. Perhaps the intent is that errors and their handling are specific to the domain where callbags are being deployed, are a type of “data” to be passed, and up to the user to recognize in that data stream.

3. I obviously haven’t given this as much thought as the creators, but wonder if errors would be an appropriate use of one of the reserved types?

It would be nice to be able to write something like:
```
pipe(
  fromIter( ... ),
  forEach( ... ),
  catch( ... )
);
```

4. Alternately, if (2) (or some variant) is the case, a brief statement of intent related to errors in the spec could answer this.

Thank you for this contribution to the community!

**Comment by staltz** [comment]
Hi @zebulonj ! :)
Errors are mentioned quickly in the spec, they are a kind of termination: https://github.com/callbag/callbag#protocol

`cb(2)` means successful termination and `cb(2, err)` means failed termination (like in RxJS), so we don't need to use one of the reserved codes for that. Then, it's up to the sink (which can be an operator) to decide what to do with that message. It's certainly possible to build `catch`, it would be roughly like `concat`, because `concat` will execute more callbags upon the current callbag sending `2`, while `catch` should execute more callbags upon the current callbag sending `2, err`.

The spec is unopinionated in that it only specifies what must happen between a single producer and a single consumer. On a larger scope, you can do anything as long as the microscopic interactions follow the spec.

**Comment by zebulonj** [comment]
Thanks! I saw that reference, but didn’t make the connection back to it when I started thinking about errors. Perfect.
